### ISSUE TITLE
Eventually add note about easier method

### ISSUE THREAD

**Issue by Jakob-Koschel** [inceabdullah/RN-Container-with-ADB-Real-Device#1]
First of all: this worked flawlessly and was incredibly helpful! Thank you very much!

I was really confused that the ssh port forwarding was necessary. Eventually I got it working by:

* adding the port 5037 to the docker ports shared between host and container.
* run `adb -H host.docker.internal devices` which will automatically resolve to the IP of the host

Eventually you would want to add  a short note for anyone stumbling over this in the future.

**Comment by vipulwairagade** [comment]
@Jakob-Koschel It is listing my devices inside docker container with the approach you mentioned. But how would `yarn android` get this device, it is throwing me error. 

```
root@70f9e8bcd8fa:/app# adb -H host.docker.internal devices
List of devices attached
32002dbbc08b95ef        device

root@70f9e8bcd8fa:/app# yarn android
yarn run v1.22.18
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1050 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
/usr/bin/env: 'sh\r': No such file or directory

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/usr/bin/env: 'sh\r': No such file or directory

    at makeError (/app/node_modules/execa/index.js:174:9)
    at /app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)  
    at async Command.handleAction (/app/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@70f9e8bcd8fa:/app# 
```

**Comment by Jakob-Koschel** [comment]
I'm afraid I don't know. This sounds like you run windows? A google search pops this up:
https://stackoverflow.com/questions/61003630/why-docker-image-build-throws-usr-bin-env-sh-r-no-such-file-or-directory

But I'm afraid it has nothing strictly to do with the adb issue I was trying to solve and is more related to windows/gradlew.
